[package]
name = "px1-fbemu"
version = "0.1.0"
authors = ["Michelle Darcy <mdarcy137@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"minifb" = "0.13.0"
